export { default as Dashboard } from './dashboard'
export { default as Home } from './home'
export { default as Posts } from './posts'
export { default as Users } from './users'
export { default as IdolFeed } from './IdolFeed'
